#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Configure Nginx to listen on port 80 and return "Hello World!" at root
sudo sh -c 'echo "server {
    listen 80;
    location / {
        echo \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx
sudo kill $(sudo cat /var/run/nginx.pid)
sudo service nginx start
