#!/usr/bin/env bash
# Update Nginx configuration to run as nginx user
# Modify permissions to allow nginx user to access necessary files
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
